name: Update Gemfile.lock

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-gemfile-lock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # Adjust the Ruby version as needed

    - name: Update Gemfile.lock
      run: |
        sed -i 's/aarch64/x86_64/g' Gemfile.lock
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Gemfile.lock
        git commit -m "Update architecture from aarch64 to x86_64 in Gemfile.lock"
        git push

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update architecture from aarch64 to x86_64 in Gemfile.lock
        branch: update-gemfile-lock
        title: Update Gemfile.lock architecture
        body: This pull request updates the architecture in Gemfile.lock from aarch64 to x86_64.
